// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: market.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Boffer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CID   string `protobuf:"bytes,1,opt,name=CID,proto3" json:"CID,omitempty"`
	IP    string `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port  int32  `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	Price int32  `protobuf:"varint,4,opt,name=Price,proto3" json:"Price,omitempty"`
}

func (x *Boffer) Reset() {
	*x = Boffer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Boffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boffer) ProtoMessage() {}

func (x *Boffer) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boffer.ProtoReflect.Descriptor instead.
func (*Boffer) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{0}
}

func (x *Boffer) GetCID() string {
	if x != nil {
		return x.CID
	}
	return ""
}

func (x *Boffer) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *Boffer) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Boffer) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

// request a specific file with a CID
type QueryOffersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CID string `protobuf:"bytes,1,opt,name=CID,proto3" json:"CID,omitempty"`
}

func (x *QueryOffersRequest) Reset() {
	*x = QueryOffersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOffersRequest) ProtoMessage() {}

func (x *QueryOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOffersRequest.ProtoReflect.Descriptor instead.
func (*QueryOffersRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{1}
}

func (x *QueryOffersRequest) GetCID() string {
	if x != nil {
		return x.CID
	}
	return ""
}

// return an array of Offer structs of the file requested
type QueryOffersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offers []*Boffer `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
}

func (x *QueryOffersResponse) Reset() {
	*x = QueryOffersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOffersResponse) ProtoMessage() {}

func (x *QueryOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOffersResponse.ProtoReflect.Descriptor instead.
func (*QueryOffersResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{2}
}

func (x *QueryOffersResponse) GetOffers() []*Boffer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type PostOfferRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offer *Boffer `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
}

func (x *PostOfferRequest) Reset() {
	*x = PostOfferRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostOfferRequest) ProtoMessage() {}

func (x *PostOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostOfferRequest.ProtoReflect.Descriptor instead.
func (*PostOfferRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{3}
}

func (x *PostOfferRequest) GetOffer() *Boffer {
	if x != nil {
		return x.Offer
	}
	return nil
}

type PostOfferResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostOfferResponse) Reset() {
	*x = PostOfferResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostOfferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostOfferResponse) ProtoMessage() {}

func (x *PostOfferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostOfferResponse.ProtoReflect.Descriptor instead.
func (*PostOfferResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{4}
}

type ListOffersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListOffersRequest) Reset() {
	*x = ListOffersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffersRequest) ProtoMessage() {}

func (x *ListOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffersRequest.ProtoReflect.Descriptor instead.
func (*ListOffersRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{5}
}

type ListOffersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offers []*Boffer `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
}

func (x *ListOffersResponse) Reset() {
	*x = ListOffersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOffersResponse) ProtoMessage() {}

func (x *ListOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOffersResponse.ProtoReflect.Descriptor instead.
func (*ListOffersResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{6}
}

func (x *ListOffersResponse) GetOffers() []*Boffer {
	if x != nil {
		return x.Offers
	}
	return nil
}

type QueryBidsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CID string `protobuf:"bytes,1,opt,name=CID,proto3" json:"CID,omitempty"`
}

func (x *QueryBidsRequest) Reset() {
	*x = QueryBidsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBidsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBidsRequest) ProtoMessage() {}

func (x *QueryBidsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBidsRequest.ProtoReflect.Descriptor instead.
func (*QueryBidsRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{7}
}

func (x *QueryBidsRequest) GetCID() string {
	if x != nil {
		return x.CID
	}
	return ""
}

type QueryBidsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bids []*Boffer `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
}

func (x *QueryBidsResponse) Reset() {
	*x = QueryBidsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryBidsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBidsResponse) ProtoMessage() {}

func (x *QueryBidsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBidsResponse.ProtoReflect.Descriptor instead.
func (*QueryBidsResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{8}
}

func (x *QueryBidsResponse) GetBids() []*Boffer {
	if x != nil {
		return x.Bids
	}
	return nil
}

type PostBidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bid *Boffer `protobuf:"bytes,1,opt,name=bid,proto3" json:"bid,omitempty"`
}

func (x *PostBidRequest) Reset() {
	*x = PostBidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBidRequest) ProtoMessage() {}

func (x *PostBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBidRequest.ProtoReflect.Descriptor instead.
func (*PostBidRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{9}
}

func (x *PostBidRequest) GetBid() *Boffer {
	if x != nil {
		return x.Bid
	}
	return nil
}

type PostBidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PostBidResponse) Reset() {
	*x = PostBidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBidResponse) ProtoMessage() {}

func (x *PostBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBidResponse.ProtoReflect.Descriptor instead.
func (*PostBidResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{10}
}

type ListBidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListBidRequest) Reset() {
	*x = ListBidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBidRequest) ProtoMessage() {}

func (x *ListBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBidRequest.ProtoReflect.Descriptor instead.
func (*ListBidRequest) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{11}
}

type ListBidResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bids []*Boffer `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
}

func (x *ListBidResponse) Reset() {
	*x = ListBidResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_market_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBidResponse) ProtoMessage() {}

func (x *ListBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBidResponse.ProtoReflect.Descriptor instead.
func (*ListBidResponse) Descriptor() ([]byte, []int) {
	return file_market_proto_rawDescGZIP(), []int{12}
}

func (x *ListBidResponse) GetBids() []*Boffer {
	if x != nil {
		return x.Bids
	}
	return nil
}

var File_market_proto protoreflect.FileDescriptor

var file_market_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x6f, 0x72, 0x63, 0x61, 0x22, 0x54, 0x0a, 0x06, 0x42, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x43, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43, 0x49, 0x44,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50,
	0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x50, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x26, 0x0a, 0x12, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x43,
	0x49, 0x44, 0x22, 0x3b, 0x0a, 0x13, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x72, 0x63, 0x61,
	0x2e, 0x42, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x22,
	0x36, 0x0a, 0x10, 0x50, 0x6f, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x42, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x52, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3a, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x42,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x22, 0x24, 0x0a,
	0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x69, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x43, 0x49, 0x44, 0x22, 0x35, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x69, 0x64, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x42, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x0e, 0x50, 0x6f,
	0x73, 0x74, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x03,
	0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x72, 0x63, 0x61,
	0x2e, 0x42, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x03, 0x62, 0x69, 0x64, 0x22, 0x11, 0x0a, 0x0f,
	0x50, 0x6f, 0x73, 0x74, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x10, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x33, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x42, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x32, 0x89, 0x03, 0x0a, 0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x12, 0x44, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73,
	0x12, 0x18, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6f, 0x72, 0x63,
	0x61, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x74, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6f,
	0x72, 0x63, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0d, 0x6c, 0x69, 0x73, 0x74, 0x41,
	0x6c, 0x6c, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x12, 0x17, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x09, 0x71, 0x75, 0x65, 0x72, 0x79, 0x42, 0x69, 0x64, 0x73, 0x12, 0x16, 0x2e, 0x6f, 0x72, 0x63,
	0x61, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42, 0x69, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x42,
	0x69, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x07, 0x70, 0x6f, 0x73, 0x74, 0x42, 0x69, 0x64, 0x12, 0x14, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e,
	0x50, 0x6f, 0x73, 0x74, 0x42, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x42,
	0x69, 0x64, 0x73, 0x12, 0x14, 0x2e, 0x6f, 0x72, 0x63, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6f, 0x72, 0x63, 0x61,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_market_proto_rawDescOnce sync.Once
	file_market_proto_rawDescData = file_market_proto_rawDesc
)

func file_market_proto_rawDescGZIP() []byte {
	file_market_proto_rawDescOnce.Do(func() {
		file_market_proto_rawDescData = protoimpl.X.CompressGZIP(file_market_proto_rawDescData)
	})
	return file_market_proto_rawDescData
}

var file_market_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_market_proto_goTypes = []interface{}{
	(*Boffer)(nil),              // 0: orca.Boffer
	(*QueryOffersRequest)(nil),  // 1: orca.QueryOffersRequest
	(*QueryOffersResponse)(nil), // 2: orca.QueryOffersResponse
	(*PostOfferRequest)(nil),    // 3: orca.PostOfferRequest
	(*PostOfferResponse)(nil),   // 4: orca.PostOfferResponse
	(*ListOffersRequest)(nil),   // 5: orca.ListOffersRequest
	(*ListOffersResponse)(nil),  // 6: orca.ListOffersResponse
	(*QueryBidsRequest)(nil),    // 7: orca.QueryBidsRequest
	(*QueryBidsResponse)(nil),   // 8: orca.QueryBidsResponse
	(*PostBidRequest)(nil),      // 9: orca.PostBidRequest
	(*PostBidResponse)(nil),     // 10: orca.PostBidResponse
	(*ListBidRequest)(nil),      // 11: orca.ListBidRequest
	(*ListBidResponse)(nil),     // 12: orca.ListBidResponse
}
var file_market_proto_depIdxs = []int32{
	0,  // 0: orca.QueryOffersResponse.offers:type_name -> orca.Boffer
	0,  // 1: orca.PostOfferRequest.offer:type_name -> orca.Boffer
	0,  // 2: orca.ListOffersResponse.offers:type_name -> orca.Boffer
	0,  // 3: orca.QueryBidsResponse.bids:type_name -> orca.Boffer
	0,  // 4: orca.PostBidRequest.bid:type_name -> orca.Boffer
	0,  // 5: orca.ListBidResponse.bids:type_name -> orca.Boffer
	1,  // 6: orca.Market.queryOffers:input_type -> orca.QueryOffersRequest
	3,  // 7: orca.Market.postOffer:input_type -> orca.PostOfferRequest
	5,  // 8: orca.Market.listAllOffers:input_type -> orca.ListOffersRequest
	7,  // 9: orca.Market.queryBids:input_type -> orca.QueryBidsRequest
	9,  // 10: orca.Market.postBid:input_type -> orca.PostBidRequest
	11, // 11: orca.Market.listBids:input_type -> orca.ListBidRequest
	2,  // 12: orca.Market.queryOffers:output_type -> orca.QueryOffersResponse
	4,  // 13: orca.Market.postOffer:output_type -> orca.PostOfferResponse
	6,  // 14: orca.Market.listAllOffers:output_type -> orca.ListOffersResponse
	8,  // 15: orca.Market.queryBids:output_type -> orca.QueryBidsResponse
	10, // 16: orca.Market.postBid:output_type -> orca.PostBidResponse
	12, // 17: orca.Market.listBids:output_type -> orca.ListBidResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_market_proto_init() }
func file_market_proto_init() {
	if File_market_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_market_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Boffer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOffersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOffersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostOfferRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostOfferResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOffersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOffersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBidsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryBidsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostBidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostBidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_market_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBidResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_market_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_proto_goTypes,
		DependencyIndexes: file_market_proto_depIdxs,
		MessageInfos:      file_market_proto_msgTypes,
	}.Build()
	File_market_proto = out.File
	file_market_proto_rawDesc = nil
	file_market_proto_goTypes = nil
	file_market_proto_depIdxs = nil
}
